import os

MAVLINK_DEVICE = "/dev/serial/by-id/usb-Prolific_Technology_Inc._USB-Serial_Controller_D-if00-port0"
MAVLINK_DEVICE_GLOBS = (
    "/dev/serial/by-id/*FTDI*",
    "usb-Prolific_Technology_Inc._USB-Serial_Controller_D-if00-port0",
)
MAVLINK_BAUD = 57600
LIDAR_DEVICE = "/dev/ttyAMA0"
LIDAR_BAUD = 115200

LED_DEVICE = "/dev/spidev0.0"
LED_COUNT = 25
LED_BRIGHTNESS = 0.3
LED_SPI_KHZ = 800


LOG_DIR = os.path.expanduser("~/bilbo-logs")
LOG_LEVEL = "INFO"
LOG_MAX_BYTES = 8 * 1024 * 1024
LOG_BACKUPS = 5
STATUS_LOG_INTERVAL_S = 0.5
CSV_FLUSH_INTERVAL_S = 1.0


DEBUG_CONSOLE = os.environ.get("BILBO_DEBUG_CONSOLE", "0") == "1"
DEBUG_PREVIEW = os.environ.get("BILBO_DEBUG_PREVIEW", "0") == "1"
DEBUG_DRAW = os.environ.get("BILBO_DEBUG_DRAW", "0") == "1"



TICK_HZ = 15.0
TICK_PERIOD_S = 1.0 / TICK_HZ
MIN_SETPOINT_INTERVAL_S = 1.0 / 20.0

TICK_OVERRUN_LIMIT_S = 0.5
MAX_CONSECUTIVE_FAULTS = 5

HEARTBEAT_TX_INTERVAL_S = 1.0

LINK_TIMEOUT_S = 3.0
RECONNECT_INTERVAL_S = 1.0
RC_STALE_S = 1.0
VISION_MAX_AGE_S = 0.3
MAX_VISION_FAULTS = 30  

IMAGE_WIDTH_PX = 640
IMAGE_HEIGHT_PX = 480
CAMERA_FOV_DEG = 78.0
PIXELS_PER_DEGREE = IMAGE_WIDTH_PX / CAMERA_FOV_DEG

CAMERA_IS_INVERTED = True
LIDAR_MIN_CM = 20
LIDAR_MAX_CM = 800

LIDAR_MIN_STRENGTH = 100
LIDAR_RX_BUFFER_CAP = 512
LIDAR_MAX_AGE_S = 1.0

LIDAR_MAX_JUMP_CM = 150
LIDAR_JUMP_CONFIRMS = 2
LIDAR_HEALTH_FRAMES = 5

LIDAR_HGATE_FRAC = 0.30         
LIDAR_HGATE_MIN_PX = 18         
LIDAR_HGATE_MAX_PX = 90

LIDAR_VGATE_FRAC = 0.25          
LIDAR_VGATE_MIN_PX = 20
LIDAR_VGATE_MAX_PX = 120




LIDAR_BORESIGHT_ROW_PX = IMAGE_HEIGHT_PX // 2
LIDAR_BASELINE_CM = 5.0
LIDAR_OFFSET_SIGN = 1.0
PERSON_CLASS = 0

CONF_THRESHOLD = 0.45

MIN_BOX_AREA_PX = 800

TRACK_GATE_PX = 160.0
TRACK_AREA_RATIO = 2.5





#PID SHITT
YAW_DEADBAND_FRAC = 0.18
YAW_DEADBAND_MIN_PX = 12.0
YAW_DEADBAND_MAX_PX = 55.0

YAW_DEADBAND_PX = 40.0

YAW_PID_OUTPUT_SIGN = -1.0

YAW_KP = 0.10
YAW_KI = 0.0
YAW_KD = 0.0

MAX_YAW_RATE_DEG_S = 50.0

TARGET_DISTANCE_CM = 400.0

DIST_KP = 0.006  
DIST_KI = 0.0
DIST_KD = 0.0
MAX_FORWARD_SPEED_MS = 1.0


FORWARD_SLEW_MS2 = 0.75
FORWARD_ALIGN_LIMIT_DEG = 15.0
MIN_SAFE_DISTANCE_CM = 150.0
BACKOFF_SPEED_MS = 0.4
HARD_MAX_SPEED_MS = 2.0
HARD_MAX_YAW_RATE_DEG_S = 60.0


CH_ENABLE = 8

SWITCH_MID_LOW_US = 1300
SWITCH_MID_HIGH_US = 1700
LOST_TRACK_S = 1.2


TRACK_MAX_MISSES = int(LOST_TRACK_S * TICK_HZ)
REACQUIRE_FRAMES = 3
TARGET_CONFIRM_FRAMES = 3

SEARCH_YAW_RATE_DEG_S = 35.0
SEARCH_TIMEOUT_S = 18.0
MAX_LOST_TRACK_S = 25.0

MAX_TRACK_DURATION_S = 240.0

MIN_TRACK_ALT_M = 2.0
EMERGENCY_HOLD_S = 3.0
MAX_RTL_ATTEMPTS = 2
