#!/usr/bin/env bash
#
# Install BILBO as a systemd service so it starts on boot.
#
#     sudo bash tools/install_service.sh
#
# Detects your username, repo path and virtualenv rather than making you edit
# a template, then verifies the program can actually import its dependencies
# BEFORE installing -- so you never end up with a unit that just fail-loops on
# every boot.
#
# Afterwards:
#     sudo systemctl start bilbo      run now
#     sudo systemctl enable bilbo     and on every boot
#     systemctl status bilbo          is it running?
#     journalctl -u bilbo -f          live log
#     sudo systemctl stop bilbo       stop (do this before bench.py -- see below)
#
set -euo pipefail

UNIT_NAME=bilbo
UNIT_PATH="/etc/systemd/system/${UNIT_NAME}.service"

# ---------------------------------------------------------------- detect ----

if [[ $EUID -ne 0 ]]; then
    echo "This installs into /etc/systemd/system, so it needs root:" >&2
    echo "    sudo bash tools/install_service.sh" >&2
    exit 1
fi

# The real user, not root, even under sudo.
RUN_USER="${SUDO_USER:-$(logname 2>/dev/null || echo "")}"
if [[ -z "$RUN_USER" || "$RUN_USER" == "root" ]]; then
    echo "Could not determine a non-root user to run as." >&2
    echo "Re-run with: sudo bash tools/install_service.sh" >&2
    exit 1
fi
RUN_GROUP="$(id -gn "$RUN_USER")"
HOME_DIR="$(getent passwd "$RUN_USER" | cut -d: -f6)"

# Repo root = parent of the directory holding this script.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "${SCRIPT_DIR}/.." && pwd)"
MAIN="${REPO}/detectors/main.py"

if [[ ! -f "$MAIN" ]]; then
    echo "Cannot find ${MAIN}. Run this from inside the BILBO repo." >&2
    exit 1
fi

# Find an interpreter that can actually import the flight dependencies.
PYTHON=""
for candidate in \
    "${REPO}/detectors/venv/bin/python" \
    "${HOME_DIR}/bilbo-venv/bin/python" \
    "${REPO}/.venv/bin/python" \
    "${HOME_DIR}/.virtualenvs/bilbo/bin/python" \
    "$(command -v python3 || true)"
do
    [[ -x "$candidate" ]] || continue
    if sudo -u "$RUN_USER" "$candidate" -c \
        "import pymavlink, serial, simple_pid, picamera2" >/dev/null 2>&1; then
        PYTHON="$candidate"
        break
    fi
done

if [[ -z "$PYTHON" ]]; then
    echo "No interpreter found that can import pymavlink, pyserial, simple_pid" >&2
    echo "and picamera2. Create the venv with system site-packages first:" >&2
    echo >&2
    echo "    python3 -m venv --system-site-packages ~/bilbo-venv" >&2
    echo "    source ~/bilbo-venv/bin/activate" >&2
    echo "    pip install -r ${REPO}/requirements.txt" >&2
    echo >&2
    echo "picamera2 is an apt package and cannot be pip-installed, which is why" >&2
    echo "--system-site-packages is required." >&2
    exit 1
fi

echo "user        : ${RUN_USER}:${RUN_GROUP}"
echo "repo        : ${REPO}"
echo "interpreter : ${PYTHON}"
echo "logs        : ${HOME_DIR}/bilbo-logs"
echo

# Make sure the log directory exists and is writable by the service user.
install -d -o "$RUN_USER" -g "$RUN_GROUP" "${HOME_DIR}/bilbo-logs"

# ----------------------------------------------------------------- write ----

cat > "$UNIT_PATH" <<UNIT
# Generated by tools/install_service.sh -- re-run that rather than editing here.
[Unit]
Description=BILBO autonomous person-tracking loop
# The camera and both serial ports must exist before we grab them, or preflight
# fails and we burn a restart attempt for nothing.
After=multi-user.target systemd-udev-settle.service
Wants=systemd-udev-settle.service

[Service]
Type=simple
User=${RUN_USER}
Group=${RUN_GROUP}
# dialout = serial ports, spi = LED strip, video = camera.
SupplementaryGroups=dialout spi video gpio

WorkingDirectory=${REPO}/detectors
ExecStartPre=/bin/sleep 5
ExecStart=${PYTHON} ${MAIN}

# Preflight returns 1 when a sensor is not ready yet, which on a cold boot is
# often just the camera stack still coming up -- so retrying is correct. The
# burst limit stops it retrying forever if something is genuinely broken:
# endlessly relaunching a flight program that cannot see its sensors is worse
# than not running at all.
Restart=on-failure
RestartSec=10
StartLimitBurst=5
StartLimitIntervalSec=300

# The program writes its own rotating log and full-rate CSV to ~/bilbo-logs.
# journald only gets startup errors: stdout at loop rate is blocking I/O, and a
# consumer that stops draining the pipe would freeze the flight loop.
StandardOutput=journal
StandardError=journal

# SIGTERM runs the clean shutdown path -- zero velocity, LEDs blanked, serial
# ports closed. Give it time to finish before SIGKILL.
KillSignal=SIGTERM
TimeoutStopSec=10

[Install]
WantedBy=multi-user.target
UNIT

chmod 644 "$UNIT_PATH"
systemctl daemon-reload

echo "Installed ${UNIT_PATH}"
echo
echo "Start it now, without enabling it on boot:"
echo "    sudo systemctl start ${UNIT_NAME}"
echo "    journalctl -u ${UNIT_NAME} -f"
echo
echo "Once you trust it, make it start on every boot:"
echo "    sudo systemctl enable ${UNIT_NAME}"
echo
echo "IMPORTANT: stop the service before running bench.py, preflight_report.py"
echo "or verify_yaw_sign.py. The LiDAR port is opened exclusively and the"
echo "Pixhawk link is not shareable, so the two will fight over the hardware:"
echo "    sudo systemctl stop ${UNIT_NAME}"
